version: "3.7"

services:

  db:
    image: cassandra:latest
    expose:
           - 9042
    networks:
        db_net:
         ipv4_address: 172.100.0.10
         ipv6_address: 2001:3984:3989::10
  app:
    build: 
     context: .
     dockerfile: Dockerfile
    restart: on-failure:10
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
        db_net:
         ipv4_address: 172.100.0.9
         ipv6_address: 2001:3984:3989::09


networks:
  db_net:
    ipam:
     driver: default
     config:
       - subnet: 172.100.0.0/16
       - subnet: "2001:3984:3989::/64"
